geoip/geoip.go, geoip/geoip_test.go
Implement GeoIP location lookup in Holster. 
Given an IP, this will return the data formatted as a [GeoLocation event](https://github.com/mailgun/events/blob/master/objects.go#L52-L56) .
=> add geoip support

election/election.go
Election events would fall behind if a connection interruption occurred, This re-creates the watcher when watch falls behind on events (See https://github.com/coreos/fleet/issues/408)
=> election now handles cleared index errors 

stack/stack.go
Caller info only contained local file name which could be not unique in a project. The function name was stripped of package and receiver information that did not play well with functions like `New`, `Get`, `Start`, etc.
Besides `FuncName` function was exposed to be used by logrus-hooks to make reported function name consistent.
=> Provide more detailed caller info

waitgroup.go, waitgroup_test.go
=> WaitGroup is now threadsafe

etcdutil/README.md, etcdutil/config.go
* Added documentation for etcdutil
=> ETCD3_ENDPOINT can now accept comma separated ETCD endpoints

README.md, broadcast.go, broadcast_test.go
Added a broadcaster others might find useful.
=> Added Broadcaster

README.md, collections/README.md, go.mod, testutil/until.go, testutil/until_test.go
I've copied these or variations of these methods to 3 projects already, time they landed here.
=> Added testutil.UntilPass and testutil.UntilConnect

README.md, collections/expire_cache_test.go, errors/go113.go, go.mod, go.sum, retry/backoff.go, retry/retry.go, retry/retry_test.go, setter/setter.go, setter/setter_test.go
I've used these in scout and copied these to a few other projects, about time it went here.
=> Added setter.IsNil and retry package

README.md
Updating README per [Issue #79](https://github.com/mailgun/holster/issues/79)
Removed /v3 in links they work correctly now.
Also moved import statement for `config/GetEnv` inside code block for consistency.
=> Update REAMDE (2021-03-02)

election/election.go
Now updating to the latest term so resigning nodes don't get elected right away
=> PIP-1032: election vote now updates to the latest term

clock/rfc822.go, clock/rfc822_test.go, collections/lru_cache_test.go, discovery/memberlist.go, errors/errors.go, testutil/until.go, testutil/until_test.go
https://mailgun.atlassian.net/browse/PIP-1303
=> PIP-1303: support parsing rfc822 dataetime without day and run go fmt

tracing/tracing.go
While testing a service that traces to a remote Jaeger server, I found that much of the trace was dropped from the network.  This can be seen with command: `tcpdump -i any port 6831`.  Such as:
```
14:07:28.907657 IP 10.0.0.21.51135 > javelin.ethn.home.ambit-lm: UDP, bad length 22445 > 1472
```
The problem is OpenTelemetry is sending oversized UDP packets larger than the max 1472 bytes and the TCP stack drops them.
Tracing works fine when sending traces to Jaeger running on localhost.
=> Fix tracing over network to fit standard MTU 1500 size.

errors/errors.go, errors/go113.go, errors/go113_test.go
=> Fix errors.Wrap()/errors.Is()

tracing/tracing.go
https://mailgun.atlassian.net/browse/PIP-1618
Whoops, I accidentally a word.
=> PIP-1618: Fix typo.

go.mod, go.sum, tracing/README.md, tracing/dummy_span.go, tracing/dummy_span_test.go, tracing/level.go, tracing/mock_span_processor_test.go, tracing/scope.go, tracing/tracing.go
Depends on https://github.com/mailgun/holster/pull/122.
Drop individual spans with lower severity than log level threshold.
Defaults to Logrus log level.
=> PIP-1975: Log level

tracing/README.md, tracing/scope.go, tracing/tracing_test.go
https://mailgun.atlassian.net/browse/PIP-2241
Useful for creating trace spans only when there's an active trace.
=> PIP-2241: Implement tracing "branch" functions.

tracing/scope.go, tracing/scope_test.go
https://mailgun.atlassian.net/browse/DSU-1385
---
Before:
---
After:
---
tested with https://github.com/mailgun/spy/pull/316 and https://github.com/mailgun/spy/pull/318
=> DSU-1385 Fix BranchScope

functional/b.go, functional/functional.go, functional/functional_test.go, functional/t.go
https://mailgun.atlassian.net/browse/PIP-1682
* Fix benchmark `N` value unexpectedly not propagating to nested tests.
* Add test `Skip()`.
* Tidy code.
=> PIP-1682: Improve `functional`

functional/functional.go, functional/t.go
https://mailgun.atlassian.net/browse/PIP-1682
* Fix errors in tests.
=> PIP-1682: Fix `functional`.

tracing/dummy_span_test.go, tracing/level.go, tracing/level_test.go, tracing/scope.go
https://mailgun.atlassian.net/browse/PIP-2317
=> PIP-2317: Simplify OpenTelemetry tracing

mxresolv/mxresolv_test.go, tracing/tracing.go
https://mailgun.atlassian.net/browse/PIP-2428
* Add sampling configuration to "Initializing OpenTelemetry" log message.
=> PIP-2428: Improve logging on OTel initialization.

discovery/README.md
Small addition to `discovery/README.md` to demo usage of GetSRVAddresses() after I had a 🤦 moment with it today during local testing
=> Doc sample for GetSRVAddresses

mxresolv/mxresolv.go, mxresolv/mxresolv_test.go
The cached value was mutated on each access by concurrent goroutines causing data race.
=> PIP-2872: Fix data race in mxresolv

.github/workflows/test.yaml
Fixed in a couple draft PRs but split out to speed the fix along
=> Compose is now embedded in the Docker CLI
