- README.md
- useragent/assets/uap_regexes.yaml
- useragent/useragent.go
- useragent/useragent_test.go
Adds user agent parsing to Holster. Maintains existing constants from [Arsenal](https://github.com/mailgun/arsenal/blob/master/arsenal/useragent/__init__.py).
One item of note, `Arsenal` was previously using free data from http://user-agent-string.info/. This site has changed to https://udger.com/ which is now offering commercial packages. The previously free data is no longer available and appears they have changed the format.
> Add user-agent parsing

- README.md
- clock/README.md
- clock/clock.go
- clock/clock_test.go
- clock/frozen.go
- clock/frozen_test.go
- clock/system.go
- clock/system_test.go
Package `clock` provides the same functions as the system package `time`. In production it forwards all calls to the system `time` package, but in tests the time can be frozen by calling `Freeze` function and from that point it has to be advanced manually with `Advance` function making all scheduled calls deterministic.
The functions provided by the package have the same parameters and return values as their system counterparts with a few exceptions. Where either `*time.Timer` or `*time.Ticker` is returned by a system function, the `clock` package counterpart returns `clock.Timer` or `clock.Ticker` interface respectively. The interfaces provide API as respective `time` package structs, except `C` is not a channel, but a function that returns `<-chan time.Time`.
The `clock` package …
> Rewrite frozen time for tests

- README.md
- waitgroup.go
- waitgroup_test.go
Loop `.Until()` `.Stop()` is called
```go
var wg WaitGroup
wg.Until(func(done chan struct{}) bool {
select {
case <- time.Tick(time.Second):
// Do some periodic thing
case <- done:
return false
}
return true
})
// Close the done channel and wait for the routine to exit
wg.Stop()
```
> Added WaitGroup.Until()

- bunker/backend.go
- bunker/bunker.go
- clock/README.md
- clock/clock.go
- clock/clock_test.go
- clock/frozen_test.go
- clock/system.go
- clock_test.go
- errors/errors.go
- errors/with_context_test.go
- geoip/geoip.go
- misc.go
- misc_test.go
- priority_queue_test.go
- ttlmap_test.go
- useragent/useragent.go
- waitgroup_test.go
Made clock.Advance return how much time has passed since the time was frozen. It turned out to be very useful in tests to assert after each advance on the passed time. That makes it clear where we stand on the deterministic time scale, e.g.:
```go
c.Assert(clock.Advance(2), Equals, time.Duration(301)
```
> Return time since frozen from clock.Advance

- clock/clock.go
- clock/frozen.go
- clock/frozen_test.go
- clock/go19.go
- clock/system.go
* A set of aliases for types, constants, values and functions was added to make it possible to use the `clock` package as a drop-in replacement for the `time` package.
* Function `clock.Wait4Scheduled` was introduced to allow block test execution until the a specified number of timer events is scheduled or a timeout is expired. It is intended to be used in conjunction with `clock.Advance` to make sure that concurrently executing logic has scheduled timers/tickers to the deterministic clock before advancing time.
> Add type aliases to clock package

- waitgroup.go
Users can now manage multiple go routines with a single `WaitGroup` instance
```go
var wg holster.WaitGroup
wg.Until(func(done chan struct) bool { ... ])
wg.Until(func(done chan struct) bool { ... ])
time.Sleep(2)
wg.Stop() // Stops both go routines
```
> Until() can now manage multiple go routines

- cmd/election/main.go
- etcdutil/README.md
- etcdutil/election.go
1. Calls to `Campaign()` do not return an error if the session is cancelled or the lease the session is holding expires. It just returns as if it has gained leadership
2. The channel returned by `Observe()` does not get closed if the session is cancelled or the lease expires.
3. There is a bug in `ResumeElection()` which makes resuming elections impossible if you are already the leader. (See https://github.com/etcd-io/etcd/pull/10297)
* Re-create the session every time there is a session interrupt by listening to `session.Done()` 
* Attempt to resign leadership after connection interruption if etcd still considers us leader
* Added `election.LeaderChan()` which returns a channel users can listen on for leadership changes
* Changed signature of `etcdutil.NewElection()`
```go
e := …
```
> Election now handles connection interrupts gracefully

- clock/clock.go
- clock/frozen_test.go
- clock/go19.go
Functions `clock.Since` and `clock.Until` were using realtime regardless whether `clock.Freeze` had been called or not.
Besides `clock.Freeze` function was made to return `clock.Unfreezer` to allow one line usage: `defer clock.Freeze(clock.Now()).Unfreeze()`
> Fix clock.Since and clock.Until

- README.md
- set_default.go
Sometimes it's useful to optionally override a value if an override value exists.
```go
// Use 'SetOverride() to assign the first value that is not empty or of zero
// value.  The following will override the config file if 'foo' is provided via
// the cli or defined in the environment.
loadFromFile(&config)
argFoo = flag.String("foo", "", "foo via cli arg")
holster.SetOverride(&config.Foo, *argFoo, os.Env("FOO"))
```
> Add SetOverride()

- backoff.go
- backoff_test.go
- cmd/election/main.go
- etcdutil/README.md
- etcdutil/docker-compose.yaml
- etcdutil/election.go
- etcdutil/election_test.go
- etcdutil/session.go
- etcdutil/session_test.go
This PR Changes the usage for etcdutil.NewElection() and how it handles the election. Session disconnects and keep alive interrupts are handled gracefully.  Unlike the concurrency.Election library....
> Election rewrite

- v3/clock/README.md
- v3/clock/clock.go
- v3/clock/clock_test.go
- v3/clock/duration.go
- v3/clock/duration_test.go
- v3/clock/frozen.go
- v3/clock/frozen_test.go
- v3/clock/go19.go
- v3/clock/rfc822.go
- v3/clock/rfc822_test.go
- v3/clock/system.go
- v3/clock/system_test.go
- v3/etcdutil/README.md
- v3/etcdutil/config.go
- v3/etcdutil/docker-compose.yaml
- v3/etcdutil/election.go
- v3/etcdutil/election_test.go
- v3/etcdutil/session.go
- v3/etcdutil/session_test.go
- v3/setter/setter.go
- v3/setter/setter_test.go
We added go.mod to the repo but since it is on version v3.x.x that was not enough to claim go mod support. We have to go all the way through and adopt [Semantic Import Versioning](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). Hence `v3` is introduced here. I deliberately put only a handful of packages that mailgun/querator depends on (directly and indirectly) because some of the packages and functions here are not used anywhere and it felt like a good chance to clean things up. The selected packages are:
* `clock`
* `etcdutil`
* `setter` a new package created to contain `SetDefault` and `SetOverride` functions that used to be in `holster` package itself.
> PIP-598: Adopt go mod semantic import path

- go.mod
- go.sum
- v3/callstack/callstack.go
- v3/clock/README.md
- v3/errors/README.md
- v3/errors/bench_test.go
- v3/errors/context_map.go
- v3/errors/errors.go
- v3/errors/errors_test.go
- v3/errors/example_test.go
- v3/errors/format_test.go
- v3/errors/with_context.go
- v3/errors/with_context_test.go
- v3/etcdutil/README.md
- v3/etcdutil/backoff.go
- v3/etcdutil/config.go
- v3/etcdutil/election.go
- v3/etcdutil/session.go
- v3/etcdutil/waitgroup.go
- v3/etcdutil/waitgroup_test.go
Followup to #50, turns out packages `errors` and `callstack` are also needed. And there were a few references to the root `holster` packages left from `v3` packages.
> PIP-598: Adopt go mod semantic import path (cont.)

- v3/collections/expire_cache.go
- v3/collections/lru_cache.go
- v3/collections/lru_cache_test.go
Using clock in collection would allow for better tests against TTL.
> PIP-624: Use clock in collections

- v3/etcdutil/election.go
- v3/etcdutil/election_test.go
- v3/etcdutil/session.go
- v3/go.mod
* Function `etcdutils.NewElectionAsync` returns very fast. Unlike `etcdutil.NewElection` it does not block until the initial election is over. Caller is supposed to provide an ElectionObserver to get notified when election is completed.
* Function `etcdutil.NewElection` was refactored in terms of `etcdutils.NewElectionAsync`;
* `conf` field was dropped from `Election` because some parameters (observer, timeout) were copied over to the struct anyway. Same thing was done with `Session`;
* `etcdutils.Event` was renamed to `etcdutils.ElectionEvent` but the original spelling was preserved as a deprecated type alias to make this change non-breaking;
* `timeout` field of `Election` was renamed to `ttl` because that is what it copied from in `ElectionConfig`. Same thing was done with `Session`; …
> PIP-683: Add NewElectionAsync

- errors/context_map.go
- errors/errors.go
- errors/with_context.go
- errors/with_context_test.go
In support of the `warnings` in mime parser so warnings can report the correct line numbers when reportings warnings.
> Added NewWithDepth() WrapWithDepth()

- slice/string.go
- slice/string_test.go
This function can be usefull and more easy to use instead of "slice.ContainsString"
becasue is not necesary the user to provide modifier function. Also if the user
wants to compare a string to the items of a slice with case insensitive, he
can't rely to pass a modifier to "slice.ContainsString(...)", becasue modifier
is applied only to the element of the slice ("aA" and "Aa" will be
always not equal).
> implement a function "slice.ContainsStringIgnoreCase"

- .gitignore
- collections/README.md
- collections/lru_cache.go
- collections/lru_cache_test.go
To allow quick and efficient iteration of items in the cache such that modifications or evictions can be made within the scope of a single mutex lock.
> Added collections.LRUCache.Map()

- consul/lock.go
- consul/lock_test.go
`Lock` creates a lock file that attempts to keep the lock on the file until told to stop, even if connectivity is lost. This is a general purpose tool for coordination and can be used to gain exclusive access to a shared resource, or keep a key value pair in the KV store for the life of a service. (example: vulcand registration). It can also be used to implement a simple leader election, where the client ALWAYS attempts to reconnect and gain ownership of the lock unless told to stop.  This Implementation will however fail on the first attempt if no connectivity to consul exists. `mailgun/service` leader election has no such limitation. 
* Using the `SessionOpts.Behavior` users can dictate if the file should be deleted when `Unlock()` is called or if connectivity is lost.
> Add lock to consul package

- clock/rfc822.go
- clock/rfc822_test.go
Update RFC822Time struct to have method to return numerical offset of timezone. 
https://mailgun.atlassian.net/browse/PIP-1359
> PIP-1359: add StringWithOffset method to RFC822Time struct

- clock/rfc822.go
- clock/rfc822_test.go
- go.mod
Customers using the python api are allowed to provide the full month name in an rfc822 timestamp. This adds support for parsing rfc822 timestamps with the full month as to not break customers' integrations when api is switched over to influx. 
https://mailgun.atlassian.net/browse/PIP-1406
> PIP-1406: support parsing datetime with full month name

- clock/rfc822.go
- clock/rfc822_test.go
Some customers are omitting the seconds in a rfc2822 datetime, which per the rfc is optional. Holster should support rfc2822 datetime without seconds. 
> The time-of-day specifies the number of hours, minutes, and
>    optionally seconds since midnight of the date indicated.
https://datatracker.ietf.org/doc/html/rfc2822.html#page-14 
https://mailgun.atlassian.net/browse/PIP-1487
> PIP-1487: make seconds optional for parsing RFC822 timestamps

- clock/rfc822.go
- clock/rfc822_test.go
Customer requests are failing to parse if the month is before the day in influx but parses in the python api.  Influx needs to support it as well as customers are expecting it to parse. 
The parsing function is becoming overly complicated with multiple layouts being supported to keep parity with the python api.  This moves all possible layouts into an array and iterates through the layouts until one works or they all fail.  This brute force approach doesn't feel like the most efficient, but not too sure of how else to solve this. 
https://mailgun.atlassian.net/browse/PIP-1491
> PIP-1491: support parsing month before day

- tracing/tracing.go
It should always return a usable context.
> Fix edge condition where `InitTracing()` might return a nil context.

- mxresolv/mxresolv.go
- mxresolv/mxresolv_test.go
This pull request adds a parameter to `Lookup()` to pass a resolver. When passing `nil` we set the resolver to `net.DefaultResolver`. This is to allow the resolver to be replaced when needed, for instance when it's necessary for testing.
> Adding Resolver Passing

- tracing/README.md
- tracing/tracing.go
https://mailgun.atlassian.net/browse/PIP-1618
Simplify most common use case of OTel initialization using `tracing.NewResource()`.
before:
```
res, err := resource.Merge(
resource.Default(),
resource.NewWithAttributes(
semconv.SchemaURL,
semconv.ServiceNameKey.String("My service"),
semconv.ServiceVersionKey.String("v1.0.0"),
),
)
ctx, tracer, err := tracing.InitTracing(ctx, "github.com/myrepo/myservice", sdktrace.WithResource(res))
```
after:
```
res, err := tracing.NewResource("My service", "v1.0.0")
ctx, tracer, err := tracing.InitTracing(ctx, "github.com/myrepo/myservice", sdktrace.WithResource(res))
```
> PIP-1618: Simplify OTel resource configuration.

- tracing/tracing.go
https://mailgun.atlassian.net/browse/PIP-1618
Minor mishandling when parsing `OTEL_JAEGER_EXPORTER_PROTOCOL` setting.  Better log reflecting configured state of exporter.
> PIP-1618: OpenTelemetry protocol handling fix

- random/random.go
- random/random_test.go
Rewriting Blackbird service, we want to have an easy way to generate random domain name in tests. It has already existed in the past but been removed for no apparent. https://github.com/mailgun/holster/commit/3fa8d42131926d9f1e14ad3b4bfb30c012f5eedb#diff-561175a771283912b0ec196a3ed9d92a14f9c73e1acbe47d859ad218fea75d3d) (cc @thrawn01 for confirmation)
Since Scout is also using it https://github.com/mailgun/scout/blob/master/util/util.go, I propose to add it here as a generic randomizer instead of rewriting those functions on every service that needs it.
> PIP-1989: Re-add random utils functions

- errors/typederror.go
- tracing/scope.go
Depends on https://github.com/mailgun/holster/pull/123.
> PIP-1975: Add `TypedError` for describing errors with type classification metadata.

- tracing/README.md
- tracing/dummy_span_test.go
- tracing/level.go
- tracing/option.go
- tracing/scope.go
- tracing/tracing.go
Simplify log level usage by converting log level parameters to constant enum type.  This type mirrors `logrus.Level` exactly so it can be easily converted (e.g. `level := tracing.Level(logrus.GetLevel())`).
**Breaking Change**: This is a breaking change to the `tracing.WithLevel()` option.
Fix documentation around meaning of level numbers.
Tag spans with `log.level=<name>` and `log.levelNum=<n>`.
Using `StartScopeError()` will also tag span in error status.
> Log level improvements

- etcdutil/config.go
Fixes error when using `etcdutil` to connect to etcd "transport: authentication handshake failed: remote error: tls: protocol version not supported".
> PIP-2108: Fix TLS error connecting to etcd

- tracing/tracing.go
https://mailgun.atlassian.net/browse/PIP-2248
Closes #154
Fix timeout error occurring in unit tests for `tracing` package.
Solution was to remove an unnecessary `context.WithTimeout()` in `CloseTracing()` because the underlying call to OTel's `Shutdown()` already has a 10s timeout applied.
> PIP-2248: Fix timeout in `tracing` unit tests.

- mxresolv/mxresolv.go
- mxresolv/mxresolv_test.go
In situations where a recipient domain resolved with 2 MX hosts of the same priority only one host would be returned from `Lookup()`
* `ShuffleMXRecords()` would not consider the final entry in a list of MX records if there were only 2 entries. This change correctly identifies when the loop is on the last MX record.
> Fixed Lookup() bug

- .golangci.yml
- mxresolv/dns_test.go
- mxresolv/mxresolv.go
- mxresolv/mxresolv_test.go
`mxresolv.Lookup()` was not properly randomzing MX hosts returned in some situations.
* Tests can now `mxresolv.SetDeterministic()` to improve the quality of testing
* Switched to `mockdns` for lookups instead of relying on actual DNS records on the internet.
* Now using `r := rand.New(rand.NewSource())` instead of the global source in the rand package.
* Added tests to cover actual MX records found in the wild.
* Fixed an issue where the shuffle would ignore the last MX record in the last preference group.
* Fixed an issue where the shuffle would ignore the first MX record in the first preference group.
* Fixed an issue where prefer was ignored if there were only 2 MX records with difference preferences.
* Fixed an issue where the the first MX record would always be chosen if there were …
> mxresolv.Lookup() now properly randomized hosts in some situations

- clock/rfc822.go
- clock/rfc822_test.go
- docker-compose.yaml
- go.mod
- go.sum
- mongoutil/uri_test.go
The openapi yaml generator we use in scaffold is using `gopkg.in/yaml.v3`, which does not format `clock.RFC822` the same as the json marshaler.  It is formatting the string as `1955-11-12T06:38:00Z`, which will result in the wrong date format being displayed in response examples in the openapi yamls scaffold generates.  This updates `clock.RFC822` to support this yaml marshal/unmarshaler
- Discovered in my debugging that when calling `yaml.Marshal()` and `yaml.Unmarshal()` that it is using the `MarshalText()` and `UnmarshalText(0` methods.  This adds those methods to `clock.RFC822` so that it marshals the datetime in `clock.RFC1123` format. 
- `clock.RFC822` implements `UnmarshalText()` so that the datetime is parsed properly when unmarshaling. 
- Build was faling because docker-compose …
> add support for marshal/unmarshal gopkg.in/yaml marshaler

- consul/log.go
- docker-compose.yaml
Add GetLevel to address `*HCLogAdapter does not implement hclog.Logger (missing method GetLevel)`
> BDF-1252: Add GetLevel

- grpcconn/grpcconn.go
- mxresolv/mxresolv_test.go
* Bug: Every time when a new gRPC connection is created a new pair of `opentelementry` interceptors is also created. Those interceptors are not released when the connection is closed. Over time the number of allocated interceptors grows causing a slow memory leak. The leak is particularly pronounced in `bunker` service that repeatedly creates disposable `bunker` clients to access data in other regions. 
* Also an optional WithLogger parameter was added to the `grpcconn.NewConnMgr`
> PIP 2712: Reuse open telemetry interceptors

- slice/remove.go
- slice/remove_test.go
* Adds `slice.Remove` as a safer variant of the [slices.Delete()](https://pkg.go.dev/slices#Delete) function that avoids the panic case for invalid indecies
This function does fall within the warning about potential memory leaks if the slices modified are long-lived. See [slices.Delete()](https://pkg.go.dev/slices#Delete) docs for more info
* Remove _does_ use the same in-place approach go/x/exp uses to achieve the in-place update.
On an Intel Mac, to gut check the no-allocation claim:
```
goos: darwin
goarch: amd64
pkg: github.com/mailgun/holster/v4/slice
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkRemove-12       	242117806	         4.944 ns/op	       0 B/op	       0 allocs/op
BenchmarkRemove-12       	223956164	         4.946 ns/op	       0 B/op	       0 allocs/op …
```
> slice.Remove

- tracing/dummy_span.go
This is only in case you'd rather not merge #191 because of the minimum go version bump.
As it stands, projects with holster as indirect dependency cannot build if they also use otel v1.25.0. See also #189 
For example, a project using gubernator and otel 1.25.0 cannot build at the moment, because of this.
OTel added a new function to the Span interface, so this PR is the minimal change that can unblock things. I would prefer #191 to be merged, but either will work.
> Add AddLink method to DummySpan

- mxresolv/mxresolv.go
- mxresolv/mxresolv_test.go
Unlike `mxresolv.Lookup` function `mxresolv.LookupWithPref` returns a slice of `*net.MX` records that are ordered by preference and hostname when the preference is the same.
> PIPR-352: Add mxresolv.LookupWithPref

- docker-compose.yaml
- go.mod
On `master` branch the `toolchain` directive adds a weird side effect:
```
go version go1.21.12 darwin/arm64
go: downloading go1.22.2 (darwin/arm64)
go version go1.22.2 darwin/arm64
```
and our 1.21 CI tests test it on 1.22:
```
Run actions/setup-go@v5
Setup go version spec 1.21.x
Found in cache @ /opt/hostedtoolcache/go/1.21.10/x64
Added go to the path
Successfully set up Go version 1.21.x
go: downloading go1.22.2 (linux/amd64)
...
Cache is not found
go version go1.22.2 linux/amd64
```
https://github.com/mailgun/holster/actions/runs/9158167548/job/25175965954
but all other services are using 1.21
---
It was added in https://github.com/mailgun/holster/pull/191/files?w=1
---
What is Go Toolchains - https://go.dev/doc/toolchain
---
Tested with …
> Downgrade toolchain version

- grpcconn/grpcconn.go
Maxim said it was warning for testing/rollout and can be downgraded to info
> Changing connection pool refresh log level to info
